// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/xiaopangio/pcbook/orm/model"
)

func newScreenPanel(db *gorm.DB, opts ...gen.DOOption) screenPanel {
	_screenPanel := screenPanel{}

	_screenPanel.screenPanelDo.UseDB(db, opts...)
	_screenPanel.screenPanelDo.UseModel(&model.ScreenPanel{})

	tableName := _screenPanel.screenPanelDo.TableName()
	_screenPanel.ALL = field.NewAsterisk(tableName)
	_screenPanel.PanelID = field.NewInt32(tableName, "panel_id")
	_screenPanel.Name = field.NewString(tableName, "name")

	_screenPanel.fillFieldMap()

	return _screenPanel
}

type screenPanel struct {
	screenPanelDo

	ALL     field.Asterisk
	PanelID field.Int32
	Name    field.String

	fieldMap map[string]field.Expr
}

func (s screenPanel) Table(newTableName string) *screenPanel {
	s.screenPanelDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s screenPanel) As(alias string) *screenPanel {
	s.screenPanelDo.DO = *(s.screenPanelDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *screenPanel) updateTableName(table string) *screenPanel {
	s.ALL = field.NewAsterisk(table)
	s.PanelID = field.NewInt32(table, "panel_id")
	s.Name = field.NewString(table, "name")

	s.fillFieldMap()

	return s
}

func (s *screenPanel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *screenPanel) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 2)
	s.fieldMap["panel_id"] = s.PanelID
	s.fieldMap["name"] = s.Name
}

func (s screenPanel) clone(db *gorm.DB) screenPanel {
	s.screenPanelDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s screenPanel) replaceDB(db *gorm.DB) screenPanel {
	s.screenPanelDo.ReplaceDB(db)
	return s
}

type screenPanelDo struct{ gen.DO }

func (s screenPanelDo) Debug() *screenPanelDo {
	return s.withDO(s.DO.Debug())
}

func (s screenPanelDo) WithContext(ctx context.Context) *screenPanelDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s screenPanelDo) ReadDB() *screenPanelDo {
	return s.Clauses(dbresolver.Read)
}

func (s screenPanelDo) WriteDB() *screenPanelDo {
	return s.Clauses(dbresolver.Write)
}

func (s screenPanelDo) Session(config *gorm.Session) *screenPanelDo {
	return s.withDO(s.DO.Session(config))
}

func (s screenPanelDo) Clauses(conds ...clause.Expression) *screenPanelDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s screenPanelDo) Returning(value interface{}, columns ...string) *screenPanelDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s screenPanelDo) Not(conds ...gen.Condition) *screenPanelDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s screenPanelDo) Or(conds ...gen.Condition) *screenPanelDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s screenPanelDo) Select(conds ...field.Expr) *screenPanelDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s screenPanelDo) Where(conds ...gen.Condition) *screenPanelDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s screenPanelDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *screenPanelDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s screenPanelDo) Order(conds ...field.Expr) *screenPanelDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s screenPanelDo) Distinct(cols ...field.Expr) *screenPanelDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s screenPanelDo) Omit(cols ...field.Expr) *screenPanelDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s screenPanelDo) Join(table schema.Tabler, on ...field.Expr) *screenPanelDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s screenPanelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *screenPanelDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s screenPanelDo) RightJoin(table schema.Tabler, on ...field.Expr) *screenPanelDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s screenPanelDo) Group(cols ...field.Expr) *screenPanelDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s screenPanelDo) Having(conds ...gen.Condition) *screenPanelDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s screenPanelDo) Limit(limit int) *screenPanelDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s screenPanelDo) Offset(offset int) *screenPanelDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s screenPanelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *screenPanelDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s screenPanelDo) Unscoped() *screenPanelDo {
	return s.withDO(s.DO.Unscoped())
}

func (s screenPanelDo) Create(values ...*model.ScreenPanel) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s screenPanelDo) CreateInBatches(values []*model.ScreenPanel, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s screenPanelDo) Save(values ...*model.ScreenPanel) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s screenPanelDo) First() (*model.ScreenPanel, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScreenPanel), nil
	}
}

func (s screenPanelDo) Take() (*model.ScreenPanel, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScreenPanel), nil
	}
}

func (s screenPanelDo) Last() (*model.ScreenPanel, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScreenPanel), nil
	}
}

func (s screenPanelDo) Find() ([]*model.ScreenPanel, error) {
	result, err := s.DO.Find()
	return result.([]*model.ScreenPanel), err
}

func (s screenPanelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ScreenPanel, err error) {
	buf := make([]*model.ScreenPanel, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s screenPanelDo) FindInBatches(result *[]*model.ScreenPanel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s screenPanelDo) Attrs(attrs ...field.AssignExpr) *screenPanelDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s screenPanelDo) Assign(attrs ...field.AssignExpr) *screenPanelDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s screenPanelDo) Joins(fields ...field.RelationField) *screenPanelDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s screenPanelDo) Preload(fields ...field.RelationField) *screenPanelDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s screenPanelDo) FirstOrInit() (*model.ScreenPanel, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScreenPanel), nil
	}
}

func (s screenPanelDo) FirstOrCreate() (*model.ScreenPanel, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScreenPanel), nil
	}
}

func (s screenPanelDo) FindByPage(offset int, limit int) (result []*model.ScreenPanel, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s screenPanelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s screenPanelDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s screenPanelDo) Delete(models ...*model.ScreenPanel) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *screenPanelDo) withDO(do gen.Dao) *screenPanelDo {
	s.DO = *do.(*gen.DO)
	return s
}
