// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCPU = "cpu"

// CPU mapped from table <cpu>
type CPU struct {
	CPUID         int32   `gorm:"column:cpu_id;primaryKey;autoIncrement:true" json:"cpu_id"`
	Brand         string  `gorm:"column:brand;not null" json:"brand"`
	Name          string  `gorm:"column:name;not null" json:"name"`
	NumbersCores  int32   `gorm:"column:numbers_cores" json:"numbers_cores"`
	NumberThreads int32   `gorm:"column:number_threads" json:"number_threads"`
	MinGhz        float32 `gorm:"column:min_ghz" json:"min_ghz"`
	MaxGhz        float32 `gorm:"column:max_ghz" json:"max_ghz"`
}

// TableName CPU's table name
func (*CPU) TableName() string {
	return TableNameCPU
}
