// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGpu = "gpu"

// Gpu mapped from table <gpu>
type Gpu struct {
	GpuID    int32   `gorm:"column:gpu_id;primaryKey;autoIncrement:true" json:"gpu_id"`
	Brand    string  `gorm:"column:brand" json:"brand"`
	Name     string  `gorm:"column:name" json:"name"`
	MinGhz   float32 `gorm:"column:min_ghz" json:"min_ghz"`
	MaxGhz   float32 `gorm:"column:max_ghz" json:"max_ghz"`
	MemoryID int32   `gorm:"column:memory_id" json:"memory_id"`
}

// TableName Gpu's table name
func (*Gpu) TableName() string {
	return TableNameGpu
}
