// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKeyboard = "keyboard"

// Keyboard mapped from table <keyboard>
type Keyboard struct {
	KeyboardID int32          `gorm:"column:keyboard_id;primaryKey;autoIncrement:true" json:"keyboard_id"`
	LayoutID   int32          `gorm:"column:layout_id" json:"layout_id"`
	Backlit    bool           `gorm:"column:backlit" json:"backlit"`
	Layout     KeyboardLayout `gorm:"foreignKey:LayoutID" json:"layout"`
}

// TableName Keyboard's table name
func (*Keyboard) TableName() string {
	return TableNameKeyboard
}
