// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKeyboardLayout = "keyboard_layout"

// KeyboardLayout mapped from table <keyboard_layout>
type KeyboardLayout struct {
	LayoutID int32  `gorm:"column:layout_id;primaryKey" json:"layout_id"`
	Name     string `gorm:"column:name" json:"name"`
}

// TableName KeyboardLayout's table name
func (*KeyboardLayout) TableName() string {
	return TableNameKeyboardLayout
}
