// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLaptapGpu = "laptap_gpu"

// LaptapGpu mapped from table <laptap_gpu>
type LaptapGpu struct {
	LaptapID string `gorm:"column:laptap_id;primaryKey" json:"laptap_id"`
	GpuID    int32  `gorm:"column:gpu_id;primaryKey" json:"gpu_id"`
	Gpu      Gpu    `gorm:"foreignKey:GpuID" json:"gpu"`
}

// TableName LaptapGpu's table name
func (*LaptapGpu) TableName() string {
	return TableNameLaptapGpu
}
