// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLaptapStorage = "laptap_storage"

// LaptapStorage mapped from table <laptap_storage>
type LaptapStorage struct {
	LaptapID  string  `gorm:"column:laptap_id;primaryKey" json:"laptap_id"`
	StorageID int32   `gorm:"column:storage_id;primaryKey" json:"storage_id"`
	Storage   Storage `gorm:"foreignKey:StorageID" json:"storage"`
}

// TableName LaptapStorage's table name
func (*LaptapStorage) TableName() string {
	return TableNameLaptapStorage
}
