// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemoryUnit = "memory_unit"

// MemoryUnit mapped from table <memory_unit>
type MemoryUnit struct {
	MemoryUnitID int32  `gorm:"column:memory_unit_id;primaryKey;autoIncrement:true" json:"memory_unit_id"`
	UnitName     string `gorm:"column:unit_name" json:"unit_name"`
}

// TableName MemoryUnit's table name
func (*MemoryUnit) TableName() string {
	return TableNameMemoryUnit
}
