// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemory = "memory"

// Memory mapped from table <memory>
type Memory struct {
	MemoryID     int32      `gorm:"column:memory_id;primaryKey;autoIncrement:true" json:"memory_id"`
	Value        int32      `gorm:"column:value" json:"value"`
	MemoryUnitID int32      `gorm:"column:memory_unit_id" json:"memory_unit_id"`
	Unit         MemoryUnit `gorm:"foreignKey:MemoryUnitID" json:"unit"`
}

// TableName Memory's table name
func (*Memory) TableName() string {
	return TableNameMemory
}
