// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameScreenPanel = "screen_panel"

// ScreenPanel mapped from table <screen_panel>
type ScreenPanel struct {
	PanelID int32  `gorm:"column:panel_id;primaryKey" json:"panel_id"`
	Name    string `gorm:"column:name" json:"name"`
}

// TableName ScreenPanel's table name
func (*ScreenPanel) TableName() string {
	return TableNameScreenPanel
}
