// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStorageDriver = "storage_driver"

// StorageDriver mapped from table <storage_driver>
type StorageDriver struct {
	StorageDriverID int32  `gorm:"column:storage_driver_id;primaryKey" json:"storage_driver_id"`
	Name            string `gorm:"column:name" json:"name"`
}

// TableName StorageDriver's table name
func (*StorageDriver) TableName() string {
	return TableNameStorageDriver
}
