// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UserID         int32  `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`
	Username       string `gorm:"column:username;not null" json:"username"`
	HashedPassword string `gorm:"column:hashed_password;not null" json:"hashed_password"`
	RoleID         int32  `gorm:"column:role_id" json:"role_id"`
	Role           Role   `gorm:"foreignKey:RoleID" json:"role"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
