// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWeightUnit = "weight_unit"

// WeightUnit mapped from table <weight_unit>
type WeightUnit struct {
	WeightUnitID int32  `gorm:"column:weight_unit_id;primaryKey" json:"weight_unit_id"`
	Type         string `gorm:"column:type;primaryKey" json:"type"`
}

// TableName WeightUnit's table name
func (*WeightUnit) TableName() string {
	return TableNameWeightUnit
}
